import { useState } from "react";
import { useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";
import { Calendar, CheckCircle2, CircleDashed, ClipboardList, Grid2X2, Hourglass, List, Plus, Search, UserRound, X } from "lucide-react";
import toast from "react-hot-toast";
import { apiGet, apiPost } from "@/api/client";
import { Badge } from "@/components/ui/badge";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Pagination } from "@/components/Pagination";
import { cn, formatDate } from "@/lib/utils";
import type { OnboardingStatus, OnboardingTemplate, PaginatedResponse } from "@emp-recruit/shared";

interface EligibleApplication { id: string; stage: string; candidate_name: string; job_title: string; }
interface EnrichedChecklist { id: string; application_id: string; candidate_id: string; status: OnboardingStatus; created_at: string; candidate_name: string; job_title: string; joining_date: string | null; progress: { total: number; completed: number; percentage: number }; }
const STATUS_TABS = [
  { labelKey: "onboarding.status.all", value: "all" }, { labelKey: "onboarding.status.notStarted", value: "not_started" },
  { labelKey: "onboarding.status.inProgress", value: "in_progress" }, { labelKey: "onboarding.status.completed", value: "completed" },
] as const;
const STATUS_CONFIG: Record<string, { label: string; className: string; progress: string }> = {
  not_started: { label: "onboarding.status.notStarted", className: "bg-gray-100 text-gray-700", progress: "bg-gray-400" },
  in_progress: { label: "onboarding.status.inProgress", className: "bg-blue-50 text-blue-700", progress: "bg-brand-500" },
  completed: { label: "onboarding.status.completed", className: "bg-green-50 text-green-700", progress: "bg-green-500" },
};
const SUMMARY = [
  { status: "all", label: "Total New Hires", note: "All time", icon: UserRound, tone: "bg-violet-100 text-violet-700" },
  { status: "in_progress", label: "In Progress", note: "Active onboarding", icon: CircleDashed, tone: "bg-blue-100 text-blue-700" },
  { status: "completed", label: "Completed", note: "Ready to start", icon: CheckCircle2, tone: "bg-green-100 text-green-700" },
  { status: "not_started", label: "Not Started", note: "Needs attention", icon: Hourglass, tone: "bg-orange-100 text-orange-700" },
] as const;

export function OnboardingListPage() {
  const { t } = useTranslation(); const queryClient = useQueryClient();
  const [activeTab, setActiveTab] = useState("all"), [page, setPage] = useState(1), [search, setSearch] = useState(""), [sort, setSort] = useState("newest"), [view, setView] = useState<"grid" | "list">("grid"), [showStartModal, setShowStartModal] = useState(false);
  const [startForm, setStartForm] = useState({ application_id: "", template_id: "", joining_date: "" });
  const { data, isLoading } = useQuery({ queryKey: ["onboarding-checklists", activeTab, page], queryFn: () => apiGet<PaginatedResponse<EnrichedChecklist>>("/onboarding/checklists", { ...(activeTab !== "all" && { status: activeTab }), page, limit: 12 }) });
  const countQueries = useQueries({ queries: STATUS_TABS.map((tab) => ({ queryKey: ["onboarding-count", tab.value], queryFn: async () => (await apiGet<PaginatedResponse<EnrichedChecklist>>("/onboarding/checklists", { status: tab.value === "all" ? undefined : tab.value, page: 1, limit: 1 })).data?.total ?? 0, staleTime: 30_000 })) });
  const counts = Object.fromEntries(STATUS_TABS.map((tab, index) => [tab.value, countQueries[index]?.data ?? 0]));
  const { data: eligibleApps = [] } = useQuery({ queryKey: ["onboarding-eligible-applications"], queryFn: async () => { const [offer, hired, existing] = await Promise.all([apiGet<PaginatedResponse<EligibleApplication>>("/applications", { stage: "offer", perPage: 100 }), apiGet<PaginatedResponse<EligibleApplication>>("/applications", { stage: "hired", perPage: 100 }), apiGet<PaginatedResponse<{ application_id: string; status: OnboardingStatus }>>("/onboarding/checklists", { perPage: 200 })]); const taken = new Set((existing.data?.data ?? []).filter((item) => item.status !== "completed").map((item) => item.application_id)); return [...(offer.data?.data ?? []), ...(hired.data?.data ?? [])].filter((item) => !taken.has(item.id)); }, enabled: showStartModal });
  const { data: templatesRes } = useQuery({ queryKey: ["onboarding-templates"], queryFn: () => apiGet<(OnboardingTemplate & { task_count: number })[]>("/onboarding/templates"), enabled: showStartModal });
  const templates = templatesRes?.data ?? [];
  const startOnboarding = useMutation({ mutationFn: () => apiPost("/onboarding/checklists", startForm), onSuccess: () => { toast.success(t("onboarding.list.toastStarted")); queryClient.invalidateQueries({ queryKey: ["onboarding-checklists"] }); queryClient.invalidateQueries({ queryKey: ["onboarding-count"] }); setShowStartModal(false); setStartForm({ application_id: "", template_id: "", joining_date: "" }); }, onError: (error: any) => toast.error(error?.response?.data?.error?.message || t("onboarding.list.toastStartFailed")) });
  const payload = data?.data;
  const filtered = [...(payload?.data ?? [])].filter((item) => !search || item.candidate_name.toLowerCase().includes(search.toLowerCase()) || item.job_title.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === "newest" ? +new Date(b.created_at) - +new Date(a.created_at) : +new Date(a.created_at) - +new Date(b.created_at));
  const selectStatus = (status: string) => { setActiveTab(status); setPage(1); };

  return <div className="space-y-5 pb-8">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><ClipboardList className="h-6 w-6" /></span><div><h1 className="text-2xl font-bold text-gray-900">{t("onboarding.list.title")}</h1><p className="text-sm text-gray-500">{t("onboarding.list.subtitle")}</p></div></div><div className="flex flex-wrap gap-2"><Link to="/onboarding/templates" className={buttonVariants({ variant: "outline" })}><ClipboardList className="h-4 w-4" />{t("onboarding.list.manageTemplates")}</Link><Button onClick={() => setShowStartModal(true)}><Plus className="h-4 w-4" />{t("onboarding.list.startOnboarding")}</Button></div></header>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{SUMMARY.map(({ status, label, note, icon: Icon, tone }) => { const index = STATUS_TABS.findIndex((item) => item.value === status); return <Card key={status} className={cn("cursor-pointer transition hover:-translate-y-0.5 hover:shadow-md", activeTab === status && "border-brand-400 ring-1 ring-brand-200")} onClick={() => selectStatus(status)}><CardContent className="flex items-center gap-4 p-4"><span className={cn("flex h-12 w-12 items-center justify-center rounded-2xl", tone)}><Icon className="h-6 w-6" /></span><div><p className="text-xs font-medium text-gray-500">{label}</p>{countQueries[index]?.isLoading ? <Skeleton className="mt-1 h-7 w-10" /> : <p className="text-2xl font-bold text-gray-900">{counts[status]}</p>}<p className="text-xs text-gray-400">{note}</p></div></CardContent></Card>; })}</div>

    <Card><CardContent className="flex flex-col gap-3 p-3 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t("onboarding.list.searchPlaceholder")} className="pl-9" /></div><Select value={activeTab} onValueChange={selectStatus}><SelectTrigger className="lg:w-52"><SelectValue /></SelectTrigger><SelectContent>{STATUS_TABS.map((tab) => <SelectItem key={tab.value} value={tab.value}>{t(tab.labelKey)}</SelectItem>)}</SelectContent></Select><Select value={sort} onValueChange={setSort}><SelectTrigger className="lg:w-48"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="newest">Newest first</SelectItem><SelectItem value="oldest">Oldest first</SelectItem></SelectContent></Select><div className="flex overflow-hidden rounded-lg border border-gray-300"><Button variant="ghost" size="icon" onClick={() => setView("grid")} className={cn("rounded-none", view === "grid" && "bg-brand-50 text-brand-600")}><Grid2X2 className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => setView("list")} className={cn("rounded-none border-l border-gray-300", view === "list" && "bg-brand-50 text-brand-600")}><List className="h-4 w-4" /></Button></div></CardContent></Card>

    <div className="overflow-x-auto border-b border-gray-200"><div className="flex min-w-max gap-7">{STATUS_TABS.map((tab) => <button key={tab.value} onClick={() => selectStatus(tab.value)} className={cn("flex items-center gap-2 border-b-2 px-1 py-3 text-sm font-medium", activeTab === tab.value ? "border-brand-600 text-brand-600" : "border-transparent text-gray-500")}>{t(tab.labelKey)}<Badge variant="secondary">{counts[tab.value]}</Badge></button>)}</div></div>

    {isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <Skeleton key={index} className="h-72 rounded-xl" />)}</div> : !filtered.length ? <Card className="border-dashed"><CardContent className="flex min-h-64 flex-col items-center justify-center text-center"><span className="rounded-full bg-brand-50 p-4"><ClipboardList className="h-8 w-8 text-brand-600" /></span><h3 className="mt-4 font-semibold text-gray-900">{t("onboarding.list.emptyTitle")}</h3><p className="mt-1 text-sm text-gray-500">{t("onboarding.list.emptyDescription")}</p><Button className="mt-4" onClick={() => setShowStartModal(true)}><Plus className="h-4 w-4" />{t("onboarding.list.startOnboarding")}</Button></CardContent></Card> : <div className={cn("grid gap-4", view === "grid" ? "md:grid-cols-2 xl:grid-cols-3" : "grid-cols-1")}>{filtered.map((checklist) => <ChecklistCard key={checklist.id} checklist={checklist} t={t} compact={view === "list"} />)}</div>}

    {payload && <Pagination page={page} perPage={12} total={payload.total} onPageChange={setPage} />}

    {showStartModal && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={() => setShowStartModal(false)}><Card className="w-full max-w-md" onClick={(event) => event.stopPropagation()}><CardHeader className="flex-row items-start justify-between space-y-0"><div><CardTitle>{t("onboarding.list.startOnboarding")}</CardTitle><p className="mt-1 text-sm text-gray-500">{t("onboarding.list.startModalSubtitle")}</p></div><Button variant="ghost" size="icon" onClick={() => setShowStartModal(false)}><X className="h-5 w-5" /></Button></CardHeader><CardContent className="space-y-4"><div><label className="mb-1.5 block text-sm font-medium text-gray-700">{t("onboarding.list.applicationLabel")}</label><Select value={startForm.application_id || undefined} onValueChange={(value) => setStartForm((current) => ({ ...current, application_id: value }))}><SelectTrigger><SelectValue placeholder={eligibleApps.length ? t("onboarding.list.applicationPlaceholder") : t("onboarding.list.noEligible")} /></SelectTrigger><SelectContent>{eligibleApps.map((app) => <SelectItem key={app.id} value={app.id}>{app.candidate_name} — {app.job_title}</SelectItem>)}</SelectContent></Select></div><div><label className="mb-1.5 block text-sm font-medium text-gray-700">{t("onboarding.list.templateLabel")}</label><Select value={startForm.template_id || undefined} onValueChange={(value) => setStartForm((current) => ({ ...current, template_id: value }))}><SelectTrigger><SelectValue placeholder={t("onboarding.list.templatePlaceholder")} /></SelectTrigger><SelectContent>{templates.map((template) => <SelectItem key={template.id} value={template.id}>{template.name}{template.department ? ` — ${template.department}` : ""}</SelectItem>)}</SelectContent></Select></div><div><label className="mb-1.5 block text-sm font-medium text-gray-700">{t("onboarding.list.joiningDateLabel")}</label><Input type="date" value={startForm.joining_date} onChange={(event) => setStartForm((current) => ({ ...current, joining_date: event.target.value }))} /></div><div className="flex justify-end gap-2 pt-2"><Button variant="outline" onClick={() => setShowStartModal(false)}>{t("onboarding.templates.cancel")}</Button><Button onClick={() => startOnboarding.mutate()} disabled={!startForm.application_id || !startForm.template_id || !startForm.joining_date || startOnboarding.isPending}>{t("onboarding.list.startButton")}</Button></div></CardContent></Card></div>}
  </div>;
}

function ChecklistCard({ checklist, t, compact }: { checklist: EnrichedChecklist; t: (key: string, options?: any) => string; compact: boolean }) {
  const config = STATUS_CONFIG[checklist.status] || STATUS_CONFIG.not_started; const remaining = Math.max(0, checklist.progress.total - checklist.progress.completed); const initials = checklist.candidate_name.split(" ").map((part) => part[0]).slice(0, 2).join("");
  return <Card className="overflow-hidden transition hover:-translate-y-0.5 hover:border-brand-300 hover:shadow-md"><CardContent className={cn("p-4", compact && "md:flex md:items-center md:gap-6")}><div className={cn("flex items-start justify-between gap-3", compact && "md:w-72 md:shrink-0")}><div className="flex min-w-0 items-center gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-brand-50 text-sm font-semibold text-brand-700">{initials}</span><div className="min-w-0"><p className="truncate font-semibold text-gray-900">{checklist.candidate_name}</p><p className="truncate text-xs text-gray-500">{checklist.job_title}</p></div></div><Badge className={cn("shrink-0 border-0", config.className)}>{t(config.label)}</Badge></div><div className={cn("mt-4", compact && "md:mt-0 md:min-w-56 md:flex-1")}><div className="flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-gray-200"><div className={cn("h-full rounded-full", config.progress)} style={{ width: `${Math.min(checklist.progress.percentage, 100)}%` }} /></div><span className="text-xs font-semibold text-gray-700">{checklist.progress.percentage}%</span></div><p className="mt-1 text-xs text-gray-500">{checklist.progress.total ? t("onboarding.list.tasksCompleted", { completed: checklist.progress.completed, total: checklist.progress.total }) : t("onboarding.list.noTasksYet")}</p></div>{!compact && <div className="mt-4 rounded-lg border border-gray-200 bg-gray-50 p-3"><p className="mb-2 text-xs font-semibold text-gray-600">Checklist preview</p><PreviewRow done={checklist.progress.completed > 0} label="Completed tasks" value={String(checklist.progress.completed)} /><PreviewRow done={remaining === 0 && checklist.progress.total > 0} label="Remaining tasks" value={String(remaining)} /><PreviewRow done={checklist.progress.percentage === 100} label="Overall readiness" value={`${checklist.progress.percentage}%`} /></div>}<div className={cn("mt-4 flex items-center justify-between border-t border-gray-200 pt-3", compact && "md:mt-0 md:w-72 md:border-l md:border-t-0 md:pl-5 md:pt-0")}><p className="flex items-center gap-1.5 text-xs text-gray-500"><Calendar className="h-3.5 w-3.5" />{checklist.joining_date ? t("onboarding.list.joining", { date: formatDate(checklist.joining_date) }) : "Joining date pending"}</p><Link to={`/onboarding/${checklist.id}`} className={buttonVariants({ variant: "outline", size: "sm" })}>View Checklist</Link></div></CardContent></Card>;
}
function PreviewRow({ done, label, value }: { done: boolean; label: string; value: string }) { return <div className="flex items-center gap-2 border-t border-gray-200 py-2 first:border-t-0"><span className={cn("flex h-4 w-4 items-center justify-center rounded-full border", done ? "border-green-500 bg-green-500 text-white" : "border-gray-300")} >{done && <CheckCircle2 className="h-3 w-3" />}</span><span className="flex-1 text-xs text-gray-600">{label}</span><span className="text-xs font-medium text-gray-500">{value}</span></div>; }