import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, BriefcaseBusiness, Building2, CalendarDays, Code2, ExternalLink, FileText, IndianRupee, Linkedin, Loader2, Mail, Pencil, Phone, Plus, Send, UserRound, UsersRound, X } from "lucide-react";
import { useTranslation } from "react-i18next";
import toast from "react-hot-toast";
import type { Application, Candidate, JobPosting, PaginatedResponse } from "@emp-recruit/shared";
import { apiGet, apiPost } from "@/api/client";
import { Badge } from "@/components/ui/badge";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { cn, formatCurrency, formatDate, resolveUploadUrl } from "@/lib/utils";
import { enumLabel } from "@/lib/enums";

const STAGE_STYLE: Record<string, string> = { applied: "bg-blue-50 text-blue-700", screened: "bg-indigo-50 text-indigo-700", interview: "bg-purple-50 text-purple-700", offer: "bg-amber-50 text-amber-700", hired: "bg-green-50 text-green-700", rejected: "bg-red-50 text-red-700", withdrawn: "bg-gray-100 text-gray-700" };
function parseArray(value: unknown): string[] { if (!value) return []; if (Array.isArray(value)) return value as string[]; if (typeof value !== "string") return []; try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed : []; } catch { return []; } }

export function CandidateDetailPage() {
  const { t } = useTranslation(); const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const queryClient = useQueryClient();
  const [showApply, setShowApply] = useState(false); const [selectedJobId, setSelectedJobId] = useState("");
  const { data: candidateData, isLoading: loadingCandidate } = useQuery({ queryKey: ["candidate", id], queryFn: () => apiGet<Candidate>(`/candidates/${id}`), enabled: Boolean(id) });
  const { data: appsData, isLoading: loadingApps } = useQuery({ queryKey: ["candidate-applications", id], queryFn: () => apiGet<Application[]>(`/candidates/${id}/applications`), enabled: Boolean(id) });
  const { data: jobsData } = useQuery({ queryKey: ["open-jobs-for-apply"], queryFn: () => apiGet<PaginatedResponse<JobPosting>>("/jobs", { status: "open", perPage: 100 }), enabled: showApply });
  const candidate = candidateData?.data; const applications = appsData?.data ?? [];
  const applyMutation = useMutation({ mutationFn: () => apiPost("/applications", { job_id: selectedJobId, candidate_id: id, source: candidate?.source || "direct" }), onSuccess: () => { toast.success(t("candidates.detail.appliedSuccess")); queryClient.invalidateQueries({ queryKey: ["candidate-applications", id] }); setShowApply(false); setSelectedJobId(""); }, onError: (error: any) => toast.error(error.response?.data?.error?.message || t("candidates.detail.applyError")) });
  if (loadingCandidate) return <div className="flex justify-center py-24"><Loader2 className="h-8 w-8 animate-spin text-brand-600" /></div>;
  if (!candidate) return <div className="py-24 text-center text-gray-500">{t("candidates.detail.notFound")}</div>;
  const skills = parseArray(candidate.skills), tags = parseArray(candidate.tags), fullName = `${candidate.first_name} ${candidate.last_name}`, initials = `${candidate.first_name?.[0] ?? ""}${candidate.last_name?.[0] ?? ""}`.toUpperCase();
  const appliedJobIds = new Set(applications.map((application: any) => application.job_id));
  const availableJobs = ((jobsData?.data?.data ?? []) as JobPosting[]).filter((job) => !appliedJobIds.has(job.id)); const source = enumLabel(t, "source", candidate.source);
  const resumeName = candidate.resume_path?.split(/[\\/]/).pop() || `${fullName.replace(/\s+/g, "_")}_Resume.pdf`;
  const summary = [
    { icon: BriefcaseBusiness, label: "Experience", value: candidate.experience_years != null ? `${Number(candidate.experience_years)} years` : "—" },
    { icon: Building2, label: "Current Company", value: candidate.current_company || "—" }, { icon: UsersRound, label: "Source", value: source },
    { icon: Code2, label: "Top Skills", value: `${skills.length} skill${skills.length === 1 ? "" : "s"}` }
  ];
  return <div className="mx-auto max-w-[1400px] space-y-5 pb-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-center"><Button variant="outline" size="icon" onClick={() => navigate("/candidates")} aria-label="Back to candidates"><ArrowLeft className="h-5 w-5" /></Button><div className="flex min-w-0 flex-1 items-center gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-brand-50 text-lg font-semibold text-brand-700">{initials}</div><div className="min-w-0"><h1 className="truncate text-2xl font-bold text-gray-900">{fullName}</h1><p className="truncate text-sm text-gray-500">{candidate.current_title || "Candidate"}{candidate.current_company ? ` at ${candidate.current_company}` : ""}</p></div></div><div className="flex gap-3"><Link to={`/candidates/${id}/edit`} className={buttonVariants({ variant: "outline" })}><Pencil className="h-4 w-4" />{t("candidates.detail.edit")}</Link><Button onClick={() => setShowApply(true)}><Plus className="h-4 w-4" />{t("candidates.detail.applyToJob")}</Button></div></header>
    <Card><CardContent className="grid p-0 sm:grid-cols-2 xl:grid-cols-4">{summary.map(({ icon: Icon, label, value }, index) => <div key={label} className={cn("flex items-center gap-4 px-6 py-5", index > 0 && "border-t border-gray-200 sm:border-l sm:border-t-0", index === 2 && "sm:border-l-0 sm:border-t xl:border-l xl:border-t-0")}><Icon className="h-6 w-6 shrink-0 text-gray-400" /><div className="min-w-0"><p className="text-xs text-gray-500">{label}</p><p className="truncate text-sm font-semibold text-gray-900">{value}</p></div></div>)}</CardContent></Card>
    <div className="grid items-start gap-5 lg:grid-cols-[360px_minmax(0,1fr)]"><div className="space-y-4">
      <Card><CardHeader className="pb-4"><CardTitle className="flex items-center gap-2 text-base"><UserRound className="h-5 w-5 text-brand-600" />{t("candidates.detail.contactInformation")}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><a href={`mailto:${candidate.email}`} className="flex items-center gap-3 text-brand-600 hover:underline"><Mail className="h-4 w-4 text-gray-400" />{candidate.email}</a>{candidate.phone && <div className="flex items-center gap-3 text-gray-700"><Phone className="h-4 w-4 text-gray-400" />{candidate.phone}</div>}{candidate.linkedin_url && <a href={candidate.linkedin_url} target="_blank" rel="noreferrer" className="flex items-center gap-3 text-brand-600 hover:underline"><Linkedin className="h-4 w-4" />LinkedIn <ExternalLink className="h-3 w-3" /></a>}</CardContent></Card>
      <Card><CardHeader className="pb-4"><CardTitle className="flex items-center gap-2 text-base"><BriefcaseBusiness className="h-5 w-5 text-brand-600" />{t("candidates.detail.professional")}</CardTitle></CardHeader><CardContent className="grid grid-cols-[100px_1fr] gap-x-3 gap-y-2 text-sm"><span className="text-gray-500">Company</span><span className="font-medium text-gray-900">{candidate.current_company || "—"}</span><span className="text-gray-500">Role</span><span className="font-medium text-gray-900">{candidate.current_title || "—"}</span><span className="text-gray-500">Experience</span><span className="font-medium text-gray-900">{candidate.experience_years != null ? `${Number(candidate.experience_years)} years of experience` : "—"}</span><span className="text-gray-500">Source</span><span className="font-medium capitalize text-gray-900">{source}</span></CardContent></Card>
      <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><FileText className="h-5 w-5 text-brand-600" />{t("candidates.detail.resume")}</CardTitle></CardHeader><CardContent>{candidate.resume_path ? <div className="flex items-center gap-3 rounded-lg border border-gray-200 p-2.5"><div className="rounded-md bg-red-50 p-2 text-red-600"><FileText className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-gray-900">{resumeName}</p><p className="text-[11px] text-gray-500">PDF document</p></div><a href={resolveUploadUrl(candidate.resume_path)} target="_blank" rel="noreferrer" className={cn(buttonVariants({ variant: "outline", size: "sm" }), "px-2.5")}>View <ExternalLink className="h-3 w-3" /></a></div> : <p className="text-sm text-gray-500">No resume uploaded.</p>}</CardContent></Card>
      <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Code2 className="h-5 w-5 text-brand-600" />{t("candidates.detail.skills")}</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{skills.length ? skills.map((skill) => <Badge key={skill}>{skill}</Badge>) : <span className="text-sm text-gray-500">No skills added.</span>}{tags.map((tag) => <Badge key={tag} variant="secondary">{tag}</Badge>)}</CardContent></Card>
    </div><Card className="min-h-[560px]"><CardHeader className="border-b border-gray-200 py-5"><CardTitle className="flex items-center gap-2 text-base"><BriefcaseBusiness className="h-5 w-5 text-brand-600" />{t("candidates.detail.applicationsCount", { count: applications.length })}</CardTitle></CardHeader><CardContent className="space-y-4 p-4">{loadingApps ? <div className="flex justify-center py-20"><Loader2 className="h-7 w-7 animate-spin text-brand-600" /></div> : applications.length === 0 ? <div className="flex min-h-[420px] flex-col items-center justify-center rounded-lg border border-dashed border-gray-300 text-center"><div className="rounded-full bg-brand-50 p-4"><Send className="h-7 w-7 text-brand-600" /></div><p className="mt-4 font-medium text-gray-900">{t("candidates.detail.noApplications")}</p><Button className="mt-4" onClick={() => setShowApply(true)}><Plus className="h-4 w-4" />{t("candidates.detail.applyToJob")}</Button></div> : applications.map((app: any) => <Card key={app.id} className="overflow-hidden shadow-none"><CardContent className="p-0"><div className="p-5"><div className="flex items-start justify-between gap-4"><div><Link to={`/jobs/${app.job_id}`} className="font-semibold text-gray-900 hover:text-brand-600">{app.job_title || t("candidates.detail.job")}</Link><p className="mt-1 text-sm text-gray-500">{app.job_department || "—"}</p></div><Badge className={cn("border-0 capitalize", STAGE_STYLE[app.stage])}>{enumLabel(t, "stage", app.stage)}</Badge></div><div className="my-5 grid gap-4 border-y border-gray-200 py-4 sm:grid-cols-3"><Stat icon={CalendarDays} label="Applied on" value={formatDate(app.applied_at)} /><Stat icon={UsersRound} label="Source" value={enumLabel(t, "source", app.source)} /><Stat icon={IndianRupee} label="Expected salary" value={app.expected_salary != null ? formatCurrency(Number(app.expected_salary), "INR") : "—"} /></div><p className="text-sm font-medium text-gray-900">{t("candidates.detail.coverLetter")}</p><div className="mt-2 rounded-lg border border-gray-200 bg-gray-50 p-4 text-sm leading-6 text-gray-600">{app.cover_letter || "No cover letter was provided with this application."}</div></div><div className="flex flex-wrap items-center gap-x-3 gap-y-1 bg-brand-50 px-5 py-3 text-xs text-brand-700"><span>Applied via {enumLabel(t, "source", app.source)}</span><span>•</span><span>{formatDate(app.applied_at)}</span>{candidate.experience_years != null && <><span>•</span><span>{Number(candidate.experience_years)} years experience</span></>}</div></CardContent></Card>)}{candidate.notes && <div className="rounded-lg border border-gray-200 p-4"><p className="text-sm font-medium text-gray-900">{t("candidates.detail.notes")}</p><p className="mt-2 whitespace-pre-line text-sm text-gray-600">{candidate.notes}</p></div>}</CardContent></Card></div>
    {showApply && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={() => setShowApply(false)}><Card className="w-full max-w-md shadow-xl" onClick={(event) => event.stopPropagation()}><CardHeader className="flex-row items-center justify-between space-y-0"><CardTitle>{t("candidates.detail.applyDialogTitle")}</CardTitle><Button variant="ghost" size="icon" onClick={() => setShowApply(false)} aria-label={t("candidates.detail.close")}><X className="h-5 w-5" /></Button></CardHeader><CardContent><p className="mb-4 text-sm text-gray-500">{t("candidates.detail.applyDialogDescription", { name: fullName })}</p><label className="mb-1.5 block text-sm font-medium text-gray-700">{t("candidates.detail.openPositions")}</label><Select value={selectedJobId} onValueChange={setSelectedJobId}><SelectTrigger><SelectValue placeholder={t("candidates.detail.selectJob")} /></SelectTrigger><SelectContent>{availableJobs.map((job) => <SelectItem key={job.id} value={job.id}>{job.title}{job.department ? ` — ${job.department}` : ""}</SelectItem>)}</SelectContent></Select>{!availableJobs.length && <p className="mt-2 text-xs text-gray-500">{t("candidates.detail.noOpenJobs")}</p>}<div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={() => setShowApply(false)}>{t("candidates.detail.cancel")}</Button><Button disabled={!selectedJobId || applyMutation.isPending} onClick={() => applyMutation.mutate()}>{applyMutation.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}{t("candidates.detail.apply")}</Button></div></CardContent></Card></div>}
  </div>;
}

function Stat({ icon: Icon, label, value }: { icon: typeof CalendarDays; label: string; value: string }) { return <div className="flex gap-3"><Icon className="h-5 w-5 text-gray-400" /><div><p className="text-xs text-gray-500">{label}</p><p className="text-sm font-medium capitalize text-gray-900">{value}</p></div></div>; }